### PR TITLE
Add commands for Yosys Synthesis and FuseSoC

### LINKED ISSUE #67: Add TAP and Yosys code parsing & publishing steps to LibreCores Pipeline library
Currently, in the OpenRISC project, CI is in progress : 

1. It involves Yosys Synthesis (https://github.com/openrisc/mor1kx/pull/87 ) which requires performance plugin later to visualize the results graphically.
2. Currently, the  Jenkins pipeline checks for the or1k-tests and gives result as success or failure, that can be represented in tap format and later tap plugin of Jenkins can be used to visualize the results 

After these steps, we want to add these steps to Librecores pipeline library

### PR DESCRIPTION
**Pull request by Nancy-Chauhan**
Fixes https://github.com/librecores/librecores-ci-jenkins-server/issues/67

- [x] Implemented FuesocJobSpec & FuesocRunSpec library which executes a fusesoc job 

- [x] Implemented YosysSynthesisReport shared library for Yosys Synthesis, generalized for every Hardware  Projects. Executes Yosys synthesis and generates resource usage reports

- [x] Integrate YosysSynthesis step in openriscPipeline as: `YosysSynthesisReport(String core, String targetName, String yosysLogPath)`
 
- [x] Add Documentation

### CODE REVIEW

**Comment by Nancy-Chauhan** [comment]
@oleg-nenashev Does this looks fine? Will add more changes to it. I Need to integrate with openrisc pipeline.
It works in the isolated pipeline as : 
( Yosys synthesis && generate reports using plot plugin ) 
Can be used for any project ( General ) 

```
pipeline {
    agent any 
    stages{
        stage('yosys') {
            steps {
                yosysSynthesisReport {
					core 'mor1kx'
					target 'synth'
					logPath 'build/mor1kx_5.0-r3/synth-icestorm/yosys.log'
				}
            }
        }
    }
}
```

**Review by oleg-nenashev — COMMENTED** [review]
Looks good so far

**Comment by Nancy-Chauhan** [comment]
Hi @oleg-nenashev @stffrdhrn , This PR works completely now for openrisc pipelines. Also added documentation 

Done changes in https://github.com/openrisc/mor1kx/pull/93

**Review by oleg-nenashev — APPROVED** [review]
I will integrate that and create GitHub issues for follow-up improvements

**Pull request merged**
